version: "3"
services:
  redis:
    image: redis
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: coffee
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      PROFILE: develop
      TZ: "Asia/Seoul"
      DB_USER_NAME: "root"
      DB_USER_PASSWORD: 1234
    ports:
      - "8080:8080"
