spring:
  datasource:
    url: jdbc:h2:mem:test_db;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers:
      - 'localhost:9092'

management:
  endpoint:
    health:
      show-details: always