INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('아이스 아메리카노', 4100);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('아이스 카페라떼', 4300);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('아이스 바닐라레떼', 4500);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('핫 아메리카노', 4100);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('핫 카페라떼', 4300);
INSERT INTO `coffee`.`menu`(`menu_name`, `menu_price`)
VALUES ('핫 바닐라레떼', 4500);