name: Continuous Delivery develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  PROFILE: develop

jobs:
  build-push:
    name: Build and Push develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: ./gradlew build
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: coffee-shop
          region: ap-northeast-2
          tags: latest,${{ github.sha }}