name: Build Dev order-api-v2 Image and Push to ECR

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  APP_PROFILE: develop

jobs:
  dev-build:
    name: dev-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: ./gradlew build --debug