name: Run Unit Tests with Gradle

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test with Gradle
        run: ./gradlew test
